### ISSUE TITLE
The ring stops working

### ISSUE THREAD

**Issue by FarmLander** [DenisMasterHerobrine/AngelRing#31] opened 2022-06-19 00:30 UTC
The ring stops working after being in the air for a long time. The ring itself is charged using Flux Netrworks. Even if you discharge the ring and then charge it, the problem will remain. The list of mods and their versions are in the crash-log of the last request. Screenshots below. They show that the ring is charged, but the flight is not available

![image](https://user-images.githubusercontent.com/99757875/174461042-7c07fdba-c5ea-49a1-8102-784f2b526b9a.png)
![image](https://user-images.githubusercontent.com/99757875/174461051-2d8659a1-4a51-4bce-9135-15eb32543e2a.png)

**Comment by FarmLander** [comment] 2022-06-19 00:31
Upd:
"in the air for a long time" = 1hour afk in air

**Comment by DenisMasterHerobrine** [comment] 2022-06-19 10:11
I will look into it a bit later, but seems that Flux Networks do specific things when charging the ring in Curios slots. Probably needs more testing and investigation and adding support to this case, when rings charges in a different way (?).
However, thanks for the report.

**Comment by FarmLander** [comment] 2022-06-19 14:19
started working after restarting the server and the game

**Comment by DenisMasterHerobrine** [comment] 2022-06-22 13:52
Seems that it's just a TPS/tick-related issue getting Angel Ring not able to check for flight for some reason and it's skipped a bunch of ticks on the server side and mod didn't handled it, because it was already charged while skipping ticks. I think it's fixed in 2.0.1, but as far as I tested with public 2.0.0 w/ Flux Networks for 1.16 - not reproducible in my test worlds, so I did a "blind" fix which can potentially solve this. If anyone still reproduces the issue, please share your modpack/world, so I could reproduce to find out what's wrong. 
Thank you for reporting and cooperation.

**Comment by DenisMasterHerobrine** [comment] 2022-06-23 00:19
I have fixed this in 2.0.1. Check in your modpack if this fixes this. Feel free to reopen if something goes wrong again with Flux Networks. I couldn't reproduce it properly, but fixed the behaviour I got accidentally. Thank you for the report!

**Closed by DenisMasterHerobrine** 2022-06-23 00:19 UTC
Labels: Type: Bug, 1.16, Type: Mod Compatibility, Angel Ring 2, Status: Investigating, Status: Fixed in Dev
