### ISSUE TITLE
Being hit cause you to lose flight

### ISSUE THREAD

**Issue by robertm1771** [DenisMasterHerobrine/AngelRing#52] opened 2023-10-12 04:13 UTC
Direwolf20 1.20 pack

On a hit from anything will cause you to lose flight

**Comment by DenisMasterHerobrine** [comment] 2023-10-13 17:53
Thanks for the issue.

I cannot test Direwolf20's 1.20 pack at the moment, however, I've tested clean instances of Forge/NeoForge with Curios API and Angel Ring 2 and seems that there is no issues with flight on hit. Something weird is going on in the modpack, not the mod?
Cannot reproduce. Feel free to comment here if there will be other packs being affected by this, so I could reproduce it myself and fix it.

Tested instances:

Minecraft 1.20.1
Forge 47.1.0
Curios API 5.3.0+1.20.1 (both user and development environment) / 5.3.4+1.20.1 / 5.3.5+1.20.1
Angel Ring 2.2.2

Minecraft 1.20.1
NeoForge 47.1.76
Curios API 5.3.4+1.20.1 / 5.3.5+1.20.1
Angel Ring 2.2.2

Seems to work just fine even if I go and simply try to meet cactus/meet a mob and get punched by him or get mostly any damage from most of the sources. Flight works as intended, so I assume that there is a problem with other mods changing player's abilities for no reason/with issues?

**Comment by Tannelol** [comment] 2023-10-14 12:46
Hello, 

I am having the same issue in the same modpack.
A bit more info from my testing:

You loose creative flight in the following situations:

- Being hit or damaged while having any armor on (Mobs, Cacti etc. all cause this)
- Swapping Armor pieces also makes you loose it, curios slots are not affected, only the normal armor slots are

My guess would be that something about the armors conflicts with this mod, but I am not sure what exactly causes it.

The weird thing is that when you only have the angel ring equipped and no other armor on this bug will not appear, it only appears when armor is equipped.

**Comment by DenisMasterHerobrine** [comment] 2023-12-18 14:41
Seems to be solved already on FTB side. Going to close this for now.

**Closed by DenisMasterHerobrine** 2023-12-18 14:41 UTC
Labels: Cannot Reproduce, Type: Mod Compatibility, Angel Ring 2, Status: Investigating, 1.20
