### ISSUE TITLE
[BUG] XP cost is only visual. No experience points actually are removed from player's pull.

### ISSUE THREAD

**Issue by Patryk122PL** [DenisMasterHerobrine/AngelRing#44] opened 2023-01-20 07:29 UTC
There's something wrong with either how this mod calculates xp drain or how it applies this cost.

Sometimes I test flying with 30 levels and it clearly shows my xp is draining, but after re-login I'm back to 30 levels.
Other times I used for example 12 levels and after re-login it drained only 3-5 levels.

Also depending on configuration if you set xp cost low or high, but with short delay, then you can see visually experience bar is getting drained, but after a moment it snaps back to what it was or just slightly less then before first drain e.g. from 31.5 -> 30.5 -> 31.2 -> 30.3 -> 30.9 etc.

I've checked with only this mod, curios and JEI to verify if this was mod conflict and unfortunately no, it's still bugged.

Forge 43.2.3 - MC 1.19.2
Latest mod version.

**Comment by DenisMasterHerobrine** [comment] 2023-01-22 06:30
Thank you for creating an issue and letting me know. I will relook into it since in certain version it didn't happen and I was not able to reproduce it, but seems this is still an issue and I'm going to see if something breaks when the "de-sync" of XP is happening and XP bar begins to pull XP, but this is only a visual behaviour.

**Comment by Patryk122PL** [comment] 2023-01-22 10:15
It's definitely some sort of de-sync. I was trying while standing still and it very rarely happens. Also it's much more pronounced while above 30 levels and with more mods since the server has a lot more to do there..

I've recorded some example videos:

After re-login
https://share.icloud.com/photos/0bawJNMGjdVf3_119_AHmnRgw

Bouncing back
https://share.icloud.com/photos/01c2i1pBeOhkFrq7Mgcyo8sLA

**Comment by DenisMasterHerobrine** [comment] 2023-07-12 10:02
Seems that Angel Ring tried to read dirty XP data, so probably that was the reason, that Minecraft could send to Angel Ring raw data that wasn't already changed and Angel Ring tried to set a value that was changed much earlier than the update happened.

**Should be fixed in versions:**
_v2.0.3 for MC 1.16.5 and 1.18.2
v2.1.6 for MC 1.19.2
v2.2.0 for MC 1.20.1_

Please, let me know if this still persists in newer versions, since I couldn't reproduce it anymore after patching the check to not read dirty data.

**Comment by DenisMasterHerobrine** [comment] 2023-07-12 20:06
Nevermind.

**Closed** 2023-07-14 12:50 UTC
Labels: Type: Bug, 1.16, Angel Ring 2, 1.18, 1.19, Status: Fixed in Dev
